import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Brain, ArrowLeft, FileText, Download, Calendar, Clock } from "lucide-react";
import { Link } from "react-router-dom";
import { jsPDF } from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

interface Correction {
  id: string;
  created_at: string;
  correction_method: string;
  distortion_severity: string;
  distortion_type: string | null;
  processing_time_ms: number | null;
  notes: string | null;
}

const Reports = () => {
  const [corrections, setCorrections] = useState<Correction[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    fetchCorrections();
  }, []);

  const fetchCorrections = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        setLoading(false);
        toast({
          title: "Authentication Required",
          description: "Please sign in to view your reports",
          variant: "destructive"
        });
        return;
      }

      const { data, error } = await supabase
        .from('corrections')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error fetching corrections:', error);
        toast({
          title: "Error",
          description: "Failed to load reports",
          variant: "destructive"
        });
        return;
      }

      setCorrections(data || []);
    } catch (err) {
      console.error('Error:', err);
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = (report: Correction) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(66, 135, 245);
    doc.text("MRI Distortion Correction Report", 14, 20);
    
    // Report details
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Report ID: ${report.id}`, 14, 30);
    doc.text(`Generated: ${new Date(report.created_at).toLocaleString()}`, 14, 35);
    
    doc.setDrawColor(66, 135, 245);
    doc.line(14, 40, 196, 40);
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Processing Details", 14, 50);
    
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    doc.text(`Method: ${report.correction_method}`, 14, 60);
    doc.text(`Distortion Severity: ${report.distortion_severity}`, 14, 67);
    doc.text(`Distortion Type: ${report.distortion_type || 'N/A'}`, 14, 74);
    doc.text(`Processing Time: ${report.processing_time_ms ? `${(report.processing_time_ms / 1000).toFixed(2)}s` : 'N/A'}`, 14, 81);
    
    if (report.notes) {
      doc.setFontSize(14);
      doc.text("Notes", 14, 95);
      doc.setFontSize(10);
      const notesText = doc.splitTextToSize(report.notes, 170);
      doc.text(notesText, 14, 105);
    }
    
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This report is generated by MRI Corrector Pro", 14, 285);
    
    doc.save(`Report_${report.id.slice(0, 8)}_${new Date(report.created_at).toLocaleDateString()}.pdf`);
    
    toast({
      title: "Report Downloaded",
      description: "PDF report downloaded successfully"
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-secondary/30">
      {/* Header */}
      <header className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <Link to="/dashboard">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="h-5 w-5" />
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-primary" />
              <span className="text-xl font-bold">Correction Reports</span>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-12">
        <div className="max-w-6xl mx-auto">
          <div className="mb-8">
            <h1 className="text-4xl font-bold mb-2">Correction Reports</h1>
            <p className="text-muted-foreground">
              View and download detailed correction reports from your MRI processing history
            </p>
          </div>

          {loading ? (
            <Card className="p-12">
              <div className="text-center text-muted-foreground">
                <p>Loading your reports...</p>
              </div>
            </Card>
          ) : corrections.length === 0 ? (
            <Card className="p-12">
              <div className="text-center text-muted-foreground">
                <FileText className="h-16 w-16 mx-auto mb-4 opacity-50" />
                <p className="text-lg mb-2">No reports yet</p>
                <p className="text-sm">Process your first MRI image to create a report</p>
              </div>
            </Card>
          ) : (
            <div className="space-y-4">
              {corrections.map((report) => (
                <Card key={report.id} className="p-6 hover:shadow-[var(--shadow-medical)] transition-shadow">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-6">
                      <FileText className="h-12 w-12 text-primary" />
                      <div>
                        <h3 className="text-xl font-semibold mb-1">
                          Report #{report.id.slice(0, 8)}
                        </h3>
                        <div className="flex items-center gap-4 text-sm text-muted-foreground flex-wrap">
                          <span className="flex items-center gap-1">
                            <Calendar className="h-4 w-4" />
                            {new Date(report.created_at).toLocaleDateString()}
                          </span>
                          <span>Method: {report.correction_method}</span>
                          <span>Severity: {report.distortion_severity}</span>
                          {report.processing_time_ms && (
                            <span className="flex items-center gap-1">
                              <Clock className="h-4 w-4" />
                              {(report.processing_time_ms / 1000).toFixed(2)}s
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="px-3 py-1 rounded-full bg-green-500/20 text-green-600 text-sm font-medium">
                        Completed
                      </span>
                      <Button 
                        variant="medical"
                        onClick={() => generatePDF(report)}
                      >
                        <Download className="mr-2 h-4 w-4" />
                        Download
                      </Button>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Reports;
